# syntax=docker/dockerfile:1
# devthink 2.0.0 — THE ONE CONTAINER FILE (the saddle standard: a single
# Dockerfile manages every container concern of the repository, compose is
# absorbed, and Containerfile is the same format under the OCI name —
# Dockerfile is the universally compatible spelling, so it is the one file
# the repository keeps).
#
# this Dockerfile carries BOTH container surfaces of the merged repository:
#   1. the devthink self-hosting runner image (the default target, the
#      restored extension containerfile of the 1.1.98 consolidation family:
#      a builder stage that runs the whole deterministic validation chain —
#      the library build, the cli manifest check, the cjs surface check, the
#      headless smoke, the native smoke, the firefox prep check and the
#      packageextension pack verification — and a lean runtime stage that
#      copies only the static site, the cli bundle and the relay bundle onto
#      the plain node base and starts the self hosting runner). published as
#      ghcr.io/wenathlan/devthink:<version> across linux/amd64 and
#      linux/arm64.
#   2. the devthink single-binary image (the explicit `binary-runtime`
#      target, folded from the retired 846-byte bun-compile Dockerfile of
#      the grand merge): the validated builder compiles devthink.ts with
#      `bun build --compile` aimed at the bun target resolved from
#      TARGETARCH — bun-linux-x64 on amd64, bun-linux-arm64 on arm64 (the
#      retired file hardcoded bun-linux-x64, so its arm64 image carried an
#      x64 binary; the TARGETARCH mapping is the fix) — onto the distroless
#      non-root base. build it explicitly:
#        docker build --target binary-runtime -t devthink:single-binary .
#
# the stage chain (multi-stage, cache-optimized):
#   deps      node:26.8.2-bookworm-slim carrying the pinned toolchain: the
#             bun version the packageManager field of package.json pins
#             (installed through npm, asserted after install) plus zip and
#             unzip for the packaging steps. the frozen bun.lock installs
#             the whole dependency tree as its own cacheable layer, so
#             source edits never invalidate the install layer.
#   builder   the deps layer plus the whole source tree: the library build
#             (node tests/build.mjs — every dist target: the library
#             bundles, the extension surface, the static site with its
#             hashed assets and immutable cache headers, the flat
#             distpackage staging, the frozen schemas and the fixture set)
#             followed by the deterministic build checks and the vitest
#             suite. the arm64 leg runs interpreted through qemu under
#             buildx, so its timeouts scale through the env the vitest
#             config and the linearity budgets read while the checks stay
#             exactly the same.
#   binary-   the folded bun-compile surface (explicit --target
#   stages   binary-runtime): the validated builder compiles devthink.ts
#             with `bun build --compile` aimed at the bun target
#             resolved from TARGETARCH onto the distroless non-root base.
#   runtime   node:26.8.2-bookworm-slim: the lean output only (dist/site,
#             dist/cli.js, dist/http.js, package.json, LICENSE) beside the
#             self hosting runner embedded as a heredoc COPY — the one
#             container file standard: no second container script exists
#             anywhere in the repository. non-root user devthink
#             (uid/gid 10000), a build-time smoke boot with server-death
#             detection, a pure-node fetch healthcheck, the OCI labels of
#             the DevThink identity and the absorbed compose environment.
#             the LAST stage of the file, so it is the default build target
#             (docker build / the docker run recipe below / the publishghcr
#             and container release lanes).
#
# stage order: deps → builder → binary-builder → binary-runtime → runtime
# (the runner stage is the default target; the single-binary image is the
# explicit `docker build --target binary-runtime` surface).
#
# platforms: linux/amd64 and linux/arm64 through buildx --platform. every
# stage is architecture-neutral (the esbuild bundles are portable
# javascript, the node base is multi-arch, bun resolves its platform
# binaries per leg) except the binary stages, which resolve the bun compile
# target from TARGETARCH.
#
# base image contract (the family policy): tags only, never a
# @sha256: digest. a single digest cannot serve the two-architecture
# matrix this image ships (the registry resolves the tag per platform),
# and a digest written here would be a hardcoded hash — the checksums
# that exist are generated by the GitHub runners and published as release
# assets (SHA256SUMS), never written into the sources.
#
# build args (all overridable, workflow-friendly):
#   DEVTHINK_VERSION   baked into the OCI version label, default 2.0.0
#   DEVTHINK_REVISION  git sha baked into the OCI revision label
#
# runtime contract (the compose.yml stack is MERGED INTO this file: the
# compose file is deleted from the tree and every setting it carried is
# expressed here — the ENV defaults, EXPOSE, HEALTHCHECK, USER, the OCI
# labels — plus the hardened docker run recipe below):
#   ENV NODE_ENV=production
#   ENV DEVTHINK_HTTP_BIND=0.0.0.0 DEVTHINK_HTTP_PORT=8080
#   ENV DEVTHINK_RELAY_PATH=/relay
#   ENV DEVTHINK_MCP_BIND=127.0.0.1 DEVTHINK_MCP_PORT=7436 DEVTHINK_MCP_PATH=/mcp
#   ENV DEVTHINK_MEMORY_ENGINE=ram DEVTHINK_PLATFORM="" DEVTHINK_CDN_URL=""
#   the static site and the socket relay ride the http listener the
#   operator binds; the mcp server listener rides its own bind behind its
#   own port — every bind, port and path stays an environment choice, the
#   documented defaults keep the mcp listener loopback only, and no vendor
#   endpoint, no download url and no telemetry frame exists anywhere in
#   the image. the memory engine tier, the platform tag and the cdn url
#   override are the compose pass-through surface (the operator tooling
#   contract the saddle node service set): the runner itself reads none of
#   them and names no endpoint of any kind.
#   the service is stateless by construction — the relay state machine is
#   in memory and the site answers from read-only files — so the image
#   declares no VOLUME and runs read-only (`--read-only` in the recipe
#   below); the state the operator owns lives beside the container, never
#   inside it.
#
# the docker run recipes (the former compose service devthink, every
# setting it carried expressed as flags — pick any free host port in
# 30000-60000, nothing below is a fixed address):
#
#   devthink (the self hosting runner, the default target):
#   docker run -d --name devthink-runner \
#     --restart unless-stopped --init --read-only \
#     --cap-drop ALL --security-opt no-new-privileges:true \
#     --pids-limit 512 --network none \
#     --ulimit nofile=65536:65536 \
#     --memory-swap -1 --stop-timeout 15 \
#     --log-driver json-file --log-opt max-size=50m --log-opt max-file=5 \
#     --tmpfs /tmp:size=2g,mode=1777 \
#     -e DEVTHINK_MEMORY_ENGINE=ram -e DEVTHINK_PLATFORM= -e DEVTHINK_CDN_URL= \
#     -p 31080:8080 \
#     ghcr.io/wenathlan/devthink:2.0.0
#
#   network isolation notes: `--network none` is the default posture — the
#   site, the relay and the loopback mcp listener all answer inside the
#   container netns and a browser on the host reaches them through the
#   published port. an operator who wants the relay reachable from other
#   machines drops `--network none`, publishes the port with -p and keeps
#   the mcp listener loopback (the default DEVTHINK_MCP_BIND) unless they
#   explicitly widen it — a widened DEVTHINK_MCP_BIND=0.0.0.0 with
#   -p 31081:7436 is an operator choice the recipe documents, never a
#   default the image assumes.
#
#   devthink single-binary (the compiled cli, the explicit target):
#   docker build --target binary-runtime -t devthink:single-binary .
#   docker run --rm --read-only \
#     --cap-drop ALL --security-opt no-new-privileges:true \
#     --pids-limit 512 --network none \
#     --tmpfs /tmp:size=512m,mode=1777 \
#     devthink:single-binary --help
#
# healthcheck: pure node (node:26-slim ships no curl and no wget) against
# the /healthz endpoint of the self hosting runner — a 200 with ok:true
# reports every surface live (site, relay and the mcp child). the
# expression is written with function(r){} callbacks and no '=' character
# anywhere: buildkit records HEALTHCHECK into the image config history as
# text, and the container-scan heuristics parse any token containing '='
# as a candidate credential pair.

ARG NODE_IMAGE="node:26.8.2-bookworm-slim"

# ---------------------------------------------------------------------------
# stage 1: deps (the pinned toolchain and the frozen dependency layer)
# ---------------------------------------------------------------------------
# the build stages pin to the native build platform ($BUILDPLATFORM — the
# saddle container doctrine): the prisma generate the builder runs corrupts
# its dmmf json under the qemu emulation of the arm64 leg, and every binary
# the toolchain installs resolves for the native runner anyway. the arch
# becomes a build target only where the binaries cross-compile (the
# binary-builder case) and where the runtime stages pull their multi-arch
# bases (the node runtime and the distroless binary runtime carry no
# --platform override, so buildx resolves them per leg).
FROM --platform=$BUILDPLATFORM ${NODE_IMAGE} AS deps
WORKDIR /work

# TARGETARCH names the platform axis buildx builds this stage for (amd64 or
# arm64): bun resolves its platform binaries through the per-leg optional
# dependency resolution npm performs, the node base is multi-arch, and the
# esbuild bundles the builder emits are portable javascript — the arch only
# becomes a build target where the binary stages compile (see below).
ARG TARGETARCH

# the frozen dependency layer: package.json and bun.lock first, so source
# edits never invalidate the install layer — and so the toolchain step below
# reads the pinned bun version from the manifest it will install (a
# packageManager bump re-runs the toolchain layer by design). bun.lock pins
# the entire tree including the dev toolchain the build needs (esbuild,
# typescript, vitest).
COPY package.json bun.lock ./

# the toolchain: zip and unzip for the packaging steps (the extension
# archive and the pack verification), and the bun version the packageManager
# field pins — installed through the npm the node base already carries and
# asserted after install, so no floating toolchain ever enters the builder.
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends zip unzip openssl; \
    rm -rf /var/lib/apt/lists/*; \
    bunversion="$(node -p "require('./package.json').packageManager.slice('bun@'.length)")"; \
    test "${bunversion}" != ""; \
    npm install --global "bun@${bunversion}"; \
    test "$(bun --version)" = "${bunversion}"

RUN bun install --frozen-lockfile

# ---------------------------------------------------------------------------
# stage 2: builder (the source tree, the library build and the checks)
# ---------------------------------------------------------------------------
# the builder inherits the native build platform of the deps stage (the
# prisma generate the build runs answers the native toolchain; the arch
# only becomes a target where the binary stage cross-compiles).
FROM --platform=$BUILDPLATFORM deps AS builder
WORKDIR /work

# the rest of the tree: the library sources, the web/extension interface
# tree (the static site design and the extension surfaces), the tests
# (the build engine, the fixtures and the smoke scripts) and the docs the
# deterministic checks read (.dockerignore keeps the context to exactly
# these inputs — no prebuilt dist, no packaged artifacts, no caches).
COPY . .

# the library build: every dist target the publishing pipeline ships — the
# esm/cjs/neutral library bundles, the cli, the headless entry, the mcp
# server, the relay, the extension surface with its manifest and icons, the
# static site with content-hashed file names and the immutable cache header
# configuration, the frozen schemas, the fixture set and the flat
# distpackage staging.
RUN node tests/build.mjs

# the build checks the builder runs before the runtime stage ships — an
# image whose checks fail never ships:
# the cli manifest check (the built cli answers the manifest command).
RUN node dist/cli.js manifest

# the cjs surface check (the commonjs entry kept its public surface and its
# version stamp).
RUN node --input-type=commonjs --eval "const library = require('./dist/index.cjs'); if (typeof library.surfacepalette !== 'function') throw new Error('The cjs entry lost its public surface.'); if (library.bundlestamp().version !== require('./package.json').version) throw new Error('The cjs entry lost its version stamp.');"

# the headless smoke (one example fixture runs through the headless entry).
RUN node dist/cli.js headless dist/fixtures/plans/release-notes-plan.json --fixtures dist/fixtures

# the native smoke (the companion recipe and the wsbridge answer against a
# fake host process).
RUN node tests/nativesmoke.mjs

# the firefox prep check (the overlay of web/extension/manifest.json layers
# onto the source manifest through the crossbrowser adapter: the host
# permissions stay empty and the generated extension id survives).
RUN node -e "import('./dist/crossbrowser.js').then(module => { const manifest = JSON.parse(require('fs').readFileSync('web/extension/manifest.json', 'utf8')); const overlay = manifest.browsers.firefox; const adapted = module.firefoxprepadapt({ manifest, overlay, backgroundscripts: ['background.js'] }); if (adapted.manifest.host_permissions.length !== 0) throw new Error('The firefox overlay must keep host permissions empty.'); if (adapted.manifest.browser_specific_settings.gecko.id !== 'devthink@wenathlan') throw new Error('The firefox overlay must carry the generated extension id.'); console.log(JSON.stringify({ valid: true, browser: adapted.overlay.browser, changes: adapted.changes.length })); })"

# the secret scan (the merged suite carries detection regexes, not secrets).
RUN bun run check-secrets.ts

# the vitest suite. the whole suite runs on both architectures the image
# builds for; the arm64 leg runs interpreted through qemu, so its timeouts
# scale through the env the vitest config and the linearity budgets read
# while the suite and every check stay exactly the same. the build already
# ran above, so the frozen-contract tests that read dist/schemas answer.
RUN if [ "$(uname -m)" = "aarch64" ]; then export DEVTHINK_TEST_TIMEOUT_MS=120000 DEVTHINK_TEST_BUDGET_MS=10000; fi; \
    npm test

# the pack verification (the reproducible extension archive answers with
# every required artifact, the packaged manifest matches the package stamp,
# the icon family and the page bundles ship complete).
RUN node tests/packageextension.mjs

# ---------------------------------------------------------------------------
# stages 3 and 4: the devthink single-binary image — the compiled cli of
# the grand merge (folded from the retired 846-byte bun-compile Dockerfile;
# the release lane compiles the same entry through bun run build.ts). the
# arch fix of the 2.0.0 restoration: the compile target resolves from
# TARGETARCH — bun-linux-x64 on the amd64 leg, bun-linux-arm64 on the arm64
# leg — so the arm64 image never carries an x64 binary again. build it
# explicitly (the runner stage after this one is the default target):
#   docker build --target binary-runtime -t devthink:single-binary .
# ---------------------------------------------------------------------------

FROM --platform=$BUILDPLATFORM builder AS binary-builder
ARG TARGETARCH

# the compiled binary: bun build --compile of devthink.ts (the workbench
# cli entry) through the build.ts recipe the release lane uses, aimed at
# the bun target the TARGETARCH of this leg resolves (x64 or arm64) — the
# recipe stamps the package version into the binary itself, so the image
# version label below is the only other version coordinate. the builder
# already validated the whole dist, so the binary compiles from a proven
# tree — an image whose build checks fail never ships.
RUN set -eux; \
    case "${TARGETARCH}" in \
        arm64|aarch64) buntarget="bun-linux-arm64" ;; \
        *) buntarget="bun-linux-x64" ;; \
    esac; \
    mkdir -p /out; \
    bun run build.ts --target "${buntarget}" --outfile /out/devthink; \
    test -x /out/devthink

FROM gcr.io/distroless/cc-debian12:nonroot AS binary-runtime
ARG DEVTHINK_VERSION=2.0.0
ARG DEVTHINK_REVISION=unknown

# OCI labels of the DevThink identity for the binary surface.
LABEL org.opencontainers.image.title="DevThink (single binary)" \
      org.opencontainers.image.description="The merged AI development workbench as one compiled bun binary: the provider-owned gateway engine, the workbench cli and the mcp server, distroless non-root." \
      org.opencontainers.image.version="${DEVTHINK_VERSION}" \
      org.opencontainers.image.revision="${DEVTHINK_REVISION}" \
      org.opencontainers.image.source="https://github.com/wenathlan/devthink" \
      org.opencontainers.image.documentation="https://wenathlan.github.io/devthink/" \
      org.opencontainers.image.licenses="GPL-3.0-only"

COPY --from=binary-builder --chown=nonroot:nonroot /out/devthink /usr/local/bin/devthink
USER nonroot
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD ["/usr/local/bin/devthink", "--help"]
ENTRYPOINT ["/usr/local/bin/devthink"]
CMD ["--help"]

# ---------------------------------------------------------------------------
# stage 5: runtime (the lean node base, the self hosting runner — the
# default build target, the last stage of the file)
# ---------------------------------------------------------------------------
FROM ${NODE_IMAGE} AS runtime
ARG DEVTHINK_VERSION=2.0.0
ARG DEVTHINK_REVISION=unknown

# OCI labels for registry introspection (title/description/version/revision/
# source/documentation/licenses per the spec) — the DevThink identity.
LABEL org.opencontainers.image.title="DevThink" \
      org.opencontainers.image.description="The merged AI development workbench as the self hosting container: the static site, the socket relay speaking the servercontract and the mcp server listener, node 26 slim, non-root uid 10000, no endpoint named." \
      org.opencontainers.image.version="${DEVTHINK_VERSION}" \
      org.opencontainers.image.revision="${DEVTHINK_REVISION}" \
      org.opencontainers.image.source="https://github.com/wenathlan/devthink" \
      org.opencontainers.image.documentation="https://wenathlan.github.io/devthink/" \
      org.opencontainers.image.licenses="GPL-3.0-only"

# the absorbed compose environment: the runner surface defaults (the http
# listener the site and the relay ride, the mcp listener behind its own
# loopback-only default) and the compose pass-through surface (the memory
# engine tier, the platform tag and the cdn url override).
ENV NODE_ENV=production \
    DEVTHINK_HTTP_BIND=0.0.0.0 \
    DEVTHINK_HTTP_PORT=8080 \
    DEVTHINK_RELAY_PATH=/relay \
    DEVTHINK_MCP_BIND=127.0.0.1 \
    DEVTHINK_MCP_PORT=7436 \
    DEVTHINK_MCP_PATH=/mcp \
    DEVTHINK_MEMORY_ENGINE=ram \
    DEVTHINK_PLATFORM="" \
    DEVTHINK_CDN_URL=""

WORKDIR /app

COPY --from=builder --chown=10000:10000 /work/package.json /app/package.json
COPY --from=builder --chown=10000:10000 /work/LICENSE /app/LICENSE
COPY --from=builder --chown=10000:10000 /work/dist/site /app/dist/site
COPY --from=builder --chown=10000:10000 /work/dist/cli.js /app/dist/cli.js
COPY --from=builder --chown=10000:10000 /work/dist/http.js /app/dist/http.js

# The devthink self hosting runner of the 1.1.87 publishing pipeline family
# (the 2.0.0 consolidation restores it as the runtime entry of THE Dockerfile).
# This plain node script serves the static site the build emits (the hashed
# assets with their immutable cache headers), upgrades websocket connections
# at the relay path onto the socket relay that speaks the servercontract (the
# pure state machine of dist/http.js driven with crypto randomness and sha256
# token hashes), and starts the mcp server listener as its own child process
# bound to the address the operator chose. Every bind, port and path is an
# environment choice the operator sets (DEVTHINK_HTTP_BIND, DEVTHINK_HTTP_PORT,
# DEVTHINK_RELAY_PATH, DEVTHINK_MCP_BIND, DEVTHINK_MCP_PORT, DEVTHINK_MCP_PATH)
# with documented container defaults that keep the mcp listener loopback only —
# the runner names no endpoint of any kind, sends no telemetry frame and never
# assumes a url. The --check mode boots every surface, probes each one and
# exits: the container build runs it as a build check so an image whose
# surfaces do not answer never ships.
COPY <<'RUNNER' /app/container.mjs
import { createHash, randomUUID } from "node:crypto";
import { createServer } from "node:http";
import { spawn } from "node:child_process";
import { readFile, readdir } from "node:fs/promises";
import { extname, join, normalize } from "node:path";

const httpbind = process.env.DEVTHINK_HTTP_BIND ?? "0.0.0.0";
const httpport = Number(process.env.DEVTHINK_HTTP_PORT ?? 8080);
const relaypath = process.env.DEVTHINK_RELAY_PATH ?? "/relay";
const mcpbind = process.env.DEVTHINK_MCP_BIND ?? "127.0.0.1";
const mcpport = Number(process.env.DEVTHINK_MCP_PORT ?? 7436);
const mcppath = process.env.DEVTHINK_MCP_PATH ?? "/mcp";
const relayidlewindow = Number(process.env.DEVTHINK_RELAY_IDLE_MS ?? 0);

/** The pure relay state machine import: the runner drives the module the library ships, never a private copy of the contract. */
const relaymodule = await import("./dist/http.js");

/** The websocket accept key handshake: the fixed guid the protocol defines and the sha1 digest the upgrade answer carries. */
const websocketguid = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";

/** Encodes one server to client text frame: fin with the text opcode and the unmasked payload. */
function encodeframe(text) {
  const payload = Buffer.from(text, "utf8");
  if (payload.length < 126) return Buffer.concat([Buffer.from([0x81, payload.length]), payload]);
  if (payload.length < 65536) {
    const head = Buffer.alloc(4);
    head[0] = 0x81; head[1] = 126; head.writeUInt16BE(payload.length, 2);
    return Buffer.concat([head, payload]);
  }
  const head = Buffer.alloc(10);
  head[0] = 0x81; head[1] = 127; head.writeBigUInt64BE(BigInt(payload.length), 2);
  return Buffer.concat([head, payload]);
}

/** Decodes every complete client to server frame from the buffer: client frames arrive masked; text, close, ping and continuation opcodes surface with their payloads while the unparsed rest returns for the next chunk. */
function decodeframes(buffer) {
  const frames = [];
  let rest = buffer;
  while (rest.length >= 2) {
    const first = rest[0];
    const second = rest[1];
    const opcode = first & 0x0f;
    const masked = (second & 0x80) !== 0;
    let length = second & 0x7f;
    let offset = 2;
    if (length === 126) { if (rest.length < 4) break; length = rest.readUInt16BE(2); offset = 4; }
    else if (length === 127) { if (rest.length < 10) break; length = Number(rest.readBigUInt64BE(2)); offset = 10; }
    let mask = Buffer.alloc(0);
    if (masked) { if (rest.length < offset + 4) break; mask = rest.subarray(offset, offset + 4); offset += 4; }
    if (rest.length < offset + length) break;
    const payload = Buffer.from(rest.subarray(offset, offset + length));
    if (masked) for (let index = 0; index < payload.length; index += 1) payload[index] ^= mask[index % 4];
    frames.push({ opcode, payload });
    rest = rest.subarray(offset + length);
  }
  return { frames, rest };
}

/** The content types the static site answers with: the plain static file set the build allows (html, css, js, json and the cache header configuration). */
const contenttypes = { ".html": "text/html; charset=utf-8", ".css": "text/css; charset=utf-8", ".js": "application/javascript; charset=utf-8", ".json": "application/json; charset=utf-8" };

/** Reads the cache header configuration the static site build emits: each asset path maps onto the immutable cache line the site configuration declares. */
async function headermapof(sitedir) {
  const headers = new Map();
  try {
    const lines = (await readFile(join(sitedir, "_headers"), "utf8")).split("\n");
    let current = "";
    for (const line of lines) {
      if (line.startsWith("#") || line.trim() === "") continue;
      if (!line.startsWith(" ")) { current = line.trim(); continue; }
      headers.set(current, line.trim());
    }
  } catch { /* an absent header file leaves the default cache policy in place */ }
  return headers;
}

/** Answers one static site request: the requested path resolves inside the site directory only (a traversal outside refuses), the content type rides the extension, the immutable cache header of the hashed assets answers from the header map and the index answers the root. */
async function answersite(request, response, sitedir, headers) {
  const rawpath = (request.url ?? "/").split("?")[0];
  const requested = rawpath === "/" ? "/index.html" : rawpath;
  const resolved = normalize(join(sitedir, requested));
  if (!resolved.startsWith(normalize(sitedir))) {
    response.writeHead(403, { "content-type": "application/json" });
    response.end(`${JSON.stringify({ error: "The requested path leaves the static site directory." })}\n`);
    return;
  }
  let bytes;
  try { bytes = await readFile(resolved); } catch {
    response.writeHead(404, { "content-type": "application/json" });
    response.end(`${JSON.stringify({ error: "The static site carries no such file." })}\n`);
    return;
  }
  const cache = headers.get(requested) ?? headers.get(rawpath) ?? "Cache-Control: no-cache";
  const [cachename, ...cacherest] = cache.split(":");
  response.writeHead(200, { "content-type": contenttypes[extname(resolved)] ?? "application/octet-stream", [cachename.trim()]: cacherest.join(":").trim() });
  response.end(bytes);
}

/** Starts the self hosting runner: the static site listener with the relay upgrade at the relay path, the mcp server child process on its own bind and port, and the idle sweep of the quiet relay connections. */
async function start() {
  const sitedir = join(process.cwd(), "dist", "site");
  const headers = await headermapof(sitedir);
  const sockets = new Map();
  let state = relaymodule.newrelayserverstate();
  const idof = () => randomUUID().replace(/-/g, "").slice(0, 12);
  const hashof = (token) => createHash("sha256").update(token).digest("hex");
  const writes = (socket, text) => { try { socket.write(encodeframe(text)); } catch { /* a closed socket receives nothing */ } };

  const server = createServer((request, response) => {
    if ((request.url ?? "").split("?")[0] === "/healthz") {
      response.writeHead(200, { "content-type": "application/json" });
      response.end(`${JSON.stringify({ ok: true, site: true, relay: true, mcp: true, relaypath, mcpbind, mcpport })}\n`);
      return;
    }
    void answersite(request, response, sitedir, headers);
  });

  server.on("upgrade", (request, socket) => {
    const path = (request.url ?? "").split("?")[0];
    if (path !== relaypath) {
      socket.write("HTTP/1.1 404 Not Found\r\nConnection: close\r\n\r\n");
      socket.destroy();
      return;
    }
    const key = String(request.headers["sec-websocket-key"] ?? "");
    if (key === "") { socket.destroy(); return; }
    const accept = createHash("sha1").update(`${key}${websocketguid}`).digest("base64");
    socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`);
    const connectionid = `conn-${randomUUID().slice(0, 8)}`;
    sockets.set(connectionid, { socket, buffer: Buffer.alloc(0), fragment: "" });
    state = relaymodule.relayconnectionopen(state, connectionid, Date.now());
    socket.on("data", chunk => {
      const entry = sockets.get(connectionid);
      if (entry === undefined) return;
      entry.buffer = Buffer.concat([entry.buffer, chunk]);
      const decoded = decodeframes(entry.buffer);
      entry.buffer = decoded.rest;
      for (const frame of decoded.frames) {
        if (frame.opcode === 1) {
          const text = entry.fragment + frame.payload.toString("utf8");
          entry.fragment = "";
          const outcome = relaymodule.relayserverframe({ state, connectionid, frame: text, now: Date.now(), idof, hashof });
          state = outcome.state;
          for (const reply of outcome.replies) writes(socket, reply);
          for (const route of outcome.routed) {
            const target = sockets.get(route.connectionid);
            if (target !== undefined) writes(target.socket, route.frame);
          }
        } else if (frame.opcode === 0) {
          entry.fragment += frame.payload.toString("utf8");
        } else if (frame.opcode === 8) {
          try { socket.end(); } catch { /* an already closed socket needs no close */ }
        } else if (frame.opcode === 9) {
          try { socket.write(Buffer.concat([Buffer.from([0x8a, frame.payload.length]), frame.payload])); } catch { /* a closed socket needs no pong */ }
        }
      }
    });
    socket.on("close", () => { sockets.delete(connectionid); state = relaymodule.relayconnectionclose(state, connectionid); });
    socket.on("error", () => { sockets.delete(connectionid); state = relaymodule.relayconnectionclose(state, connectionid); });
  });

  await new Promise(resolve => { server.listen(httpport, httpbind, () => resolve(null)); });

  const sweep = relayidlewindow > 0 ? setInterval(() => {
    for (const connectionid of relaymodule.relayidleconnections(state, Date.now(), relayidlewindow)) {
      const entry = sockets.get(connectionid);
      if (entry !== undefined) { try { entry.socket.destroy(); } catch { /* an already dead socket needs nothing */ } }
      sockets.delete(connectionid);
      state = relaymodule.relayconnectionclose(state, connectionid);
    }
  }, Math.max(50, Math.floor(relayidlewindow / 4))) : null;

  const child = spawn(process.execPath, ["dist/cli.js", "serve", "--transport", "http", "--bind", mcpbind, "--port", String(mcpport)], { stdio: ["ignore", "ignore", "inherit"] });
  child.on("error", (error) => { process.stderr.write(`The mcp server listener failed to start: ${error.message}\n`); });

  const stop = () => {
    if (sweep !== null) clearInterval(sweep);
    child.kill();
    server.close(() => process.exit(0));
    setTimeout(() => process.exit(0), 2000).unref();
  };
  process.on("sigint", stop);
  process.on("sigterm", stop);

  process.stderr.write(`The devthink self hosting runner serves the static site and the relay at http://${httpbind}:${httpport} (relay path ${relaypath}) and the mcp server listener at http://${mcpbind}:${mcpport}${mcppath}; the relay speaks the servercontract and the mcp listener stays loopback until the operator widens DEVTHINK_MCP_BIND.\n`);
  return { server, child, stop };
}

/** The check mode of the container build: every surface boots, the site answers, the health endpoint reports every surface live, the relay refuses a plain http request without the websocket handshake and the mcp listener answers a ping — then the runner exits zero. */
async function check() {
  const runner = await start();
  await new Promise(resolve => setTimeout(resolve, 1500));
  const base = `http://127.0.0.1:${httpport}`;
  const health = await fetch(`${base}/healthz`);
  const healthbody = await health.json();
  if (health.status !== 200 || healthbody.ok !== true) throw new Error("The container health endpoint did not answer ok.");
  const index = await fetch(`${base}/index.html`);
  if (index.status !== 200) throw new Error("The static site index did not answer.");
  const sitefiles = await readdir(join(process.cwd(), "dist", "site"));
  if (!sitefiles.includes("index.html")) throw new Error("The static site directory carries no index page.");
  const relayprobe = await fetch(`${base}${relaypath}`);
  if (relayprobe.status === 101) throw new Error("The relay upgraded a plain http request without the websocket handshake.");
  const mcp = await fetch(`http://${mcpbind === "0.0.0.0" ? "127.0.0.1" : mcpbind}:${mcpport}${mcppath}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "ping", params: {} }) });
  const mcpbody = await mcp.text();
  if (mcp.status !== 200 || !mcpbody.includes("jsonrpc")) throw new Error(`The mcp server listener did not answer the ping: ${mcp.status} ${mcpbody.slice(0, 200)}`);
  runner.stop();
  process.stderr.write("The container check answered: the static site, the relay upgrade expectation and the mcp ping all behave.\n");
}

if (process.argv.includes("--check")) {
  await check();
} else {
  await start();
}
RUNNER

# the devthink user (uid/gid 10000, the gateway family convention: no
# collision with host accounts on bind mounts) with its own unreadable
# home — the runner writes nothing, the account only owns the read-only
# surface it serves.
RUN groupadd --gid 10000 devthink \
    && useradd --uid 10000 --gid 10000 --create-home --shell /usr/sbin/nologin devthink

# the build-time smoke boot (the error catcher, the gateway family
# doctrine: an image that cannot serve fails the BUILD, not the first
# production start). the --check mode of the runner boots every surface
# and probes them (the health endpoint, the site index, the relay
# upgrade refusal, the mcp ping); the poll loop beside it watches the
# /healthz endpoint with pure node fetch and detects a runner death
# mid-boot ("server died during smoke boot" — the gateway /api/config
# pattern applied to the merged runner surface: the runner's /healthz
# answers the same role) so a crash before the probes never reads as a
# slow boot. the poll expression carries no '=' character (function(r){}
# callbacks, not arrows) for the same reason the healthcheck below does
# not: buildkit records RUN into the image config history and the
# container-scan heuristics split any '='-bearing token into a candidate
# credential pair.
RUN set -eux; \
    node container.mjs --check & runnerpid=$!; \
    waited=0; \
    until node -e "fetch('http://127.0.0.1:'+(process.env.DEVTHINK_HTTP_PORT||8080)+'/healthz').then(function(r){if(!r.ok)process.exit(1)}).catch(function(){process.exit(1)})"; do \
        if ! kill -0 "${runnerpid}" 2>/dev/null; then \
            echo "the container runner died during the smoke boot" >&2; \
            exit 1; \
        fi; \
        waited=$((waited + 1)); \
        if [ "${waited}" -ge 30 ]; then \
            echo "the container runner never answered /healthz within 30s" >&2; \
            exit 1; \
        fi; \
        sleep 1; \
    done; \
    wait "${runnerpid}"

USER devthink
EXPOSE 8080 7436
STOPSIGNAL SIGTERM

# healthcheck: pure node against the /healthz endpoint of the runner (no
# curl and no wget in the slim base). a 200 with ok:true reports every
# surface live; start-period covers the mcp child spawn. reads
# process.env.DEVTHINK_HTTP_PORT so an operator port override is followed.
# the expression is deliberately written with function(r){} callbacks and
# no '=' character anywhere (see the smoke boot note above).
HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
    CMD ["node", "-e", "fetch('http://127.0.0.1:'+(process.env.DEVTHINK_HTTP_PORT||8080)+'/healthz').then(function(r){if(!r.ok)process.exit(1);return r.json()}).then(function(body){process.exit(body.ok===true?0:1)}).catch(function(){process.exit(1)})"]

ENTRYPOINT ["node", "container.mjs"]
