[build]
  publish = "."

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/studio"
  to = "/studio/index.html"
  status = 200

[[redirects]]
  from = "/generate"
  to = "/generate/index.html"
  status = 200

[[redirects]]
  from = "/library"
  to = "/library/index.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/settings/index.html"
  status = 200
