[build]
  publish = "."

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/zones"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dnssec"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gateway"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/index.html"
  status = 200
