/** Reads permitted reference repositories file by file and reports workflow conventions without copying their content. */
import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = "/home/ubuntu/reviewrepos";
const repositories = ["saddle", "devthink", "e2ugh", "maene"];

function digest(data) {
  return createHash("sha256").update(data).digest("hex").slice(0, 12);
}
function role(name) {
  if (/^package(-lock)?\.json$|^bun\.lock$|^\.npmrc$|^\.nvmrc$/.test(name)) return "package and runtime metadata";
  if (/^pom\.xml$|\.csproj$|\.gemspec$/.test(name)) return "cross-ecosystem package metadata";
  if (/^readme\.md$|^architecture\.md$|^changelog\.md$|^security\.md$/i.test(name)) return "project documentation";
  if (/^dockerfile|compose/i.test(name)) return "container or orchestration definition";
  if (/\.(ts|tsx|js|cjs|mjs|java|py|cs)$/i.test(name)) return "implementation or tooling source";
  if (/^license$|policy|terms|eula|copyright|notice/i.test(name)) return "legal or governance material";
  return "root configuration or governance material";
}
function matchall(text, expression) {
  return [...text.matchAll(expression)].map((match) => match[1]).filter(Boolean);
}
function summary(path, text) {
  const name = path.split("/").pop() ?? path;
  const triggers = matchall(text, /^\s{0,2}(pull_request|push|workflow_dispatch|schedule|release|workflow_call):/gm);
  const actions = [...new Set(matchall(text, /^\s*uses:\s*([^\s#]+)/gm))];
  const commands = [...new Set(matchall(text, /^\s*run:\s*([^\n]+)/gm))];
  const signals = [];
  if (/npm publish|pnpm publish/i.test(text)) signals.push("npm publish");
  if (/mvn .*deploy|maven.*deploy/i.test(text)) signals.push("Maven deploy");
  if (/docker .*push|build-push-action/i.test(text)) signals.push("container push");
  if (/gh release create|softprops\/action-gh-release|create-release/i.test(text)) signals.push("GitHub release");
  if (/upload-artifact/i.test(text)) signals.push("artifact upload");
  if (/sha256sum|shasum|digest/i.test(text)) signals.push("digest");
  if (/permissions:/i.test(text)) signals.push("explicit permissions");
  return {
    name,
    triggers: triggers.join(", ") || "not declared",
    actions: actions.join(", ") || "none",
    commands: commands.join("; ") || "none",
    signals: signals.join(", ") || "none",
  };
}

const repositorysections = [];
for (const repository of repositories) {
  const path = join(root, repository);
  const entries = await readdir(path, { withFileTypes: true });
  const rootfiles = entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .sort();
  const rootrows = [];
  for (const name of rootfiles) {
    const content = await readFile(join(path, name));
    rootrows.push(`| ${name} | ${content.length} | ${digest(content)} | ${role(name)} |`);
  }
  const workflowpath = join(path, ".github", "workflows");
  let workflows = [];
  try {
    workflows = (await readdir(workflowpath, { withFileTypes: true }))
      .filter((entry) => entry.isFile() && /\.ya?ml$/i.test(entry.name))
      .map((entry) => entry.name)
      .sort();
  } catch {
    workflows = [];
  }
  const workflowrows = [];
  for (const name of workflows) {
    const text = await readFile(join(workflowpath, name), "utf8");
    const item = summary(name, text);
    workflowrows.push(`| ${item.name} | ${item.triggers} | ${item.signals} | ${item.actions} | ${item.commands} |`);
  }
  repositorysections.push(
    `## ${repository}\n\n### Root files read\n\n| File | Bytes | SHA-256 prefix | Classified purpose |\n| --- | ---: | --- | --- |\n${rootrows.join("\n")}\n\n### Workflows read\n\n| Workflow | Triggers | Detected release or security signals | Reusable actions | Commands |\n| --- | --- | --- | --- | --- |\n${workflowrows.join("\n") || "| none | not declared | none | none | none |"}`,
  );
}
const introduction = `# Permitted Repository Root and Workflow Audit\n\nThis report was generated by reading every root file and every GitHub workflow file, one file at a time, in the four repositories the user authorized for comparison. The report records file inventory, hashes and workflow metadata; it intentionally does not copy implementation or workflow source into Devthink.\n\nThe observed patterns will be adapted only where they fit a browser-extension package and its metadata. A detected publishing target does not mean the target is compatible, configured or authorized for this project.\n\n`;
await writeFile("docs/11.permittedworkflows.md", `${introduction}${repositorysections.join("\n\n")}`);
console.log(`Audited ${repositories.length} permitted repositories.`);
