[build]
  publish = "."

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/player"
  to = "/player/index.html"
  status = 200

[[redirects]]
  from = "/studio"
  to = "/studio/index.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery/index.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/settings/index.html"
  status = 200
