overrides:
  deepmerge-ts: 8.0.0
  esbuild: ^0.28.2
  mysql2: 3.23.1
  qs: ^6.16.0
allowBuilds:
  '@prisma/engines': false
  esbuild: true
  prisma: false
minimumReleaseAgeExclude:
  - '@mermaid-js/parser'
  - '@oxc-project/types'
  - '@rolldown/binding-android-arm-eabi'
  - '@rolldown/binding-android-arm64'
  - '@rolldown/binding-darwin-arm64'
  - '@rolldown/binding-darwin-x64'
  - '@rolldown/binding-freebsd-x64'
  - '@rolldown/binding-linux-arm-gnueabihf'
  - '@rolldown/binding-linux-arm64-gnu'
  - '@rolldown/binding-linux-arm64-musl'
  - '@rolldown/binding-linux-ppc64-gnu'
  - '@rolldown/binding-linux-s390x-gnu'
  - '@rolldown/binding-linux-x64-gnu'
  - '@rolldown/binding-linux-x64-musl'
  - '@rolldown/binding-openharmony-arm64'
  - '@rolldown/binding-win32-arm64-msvc'
  - '@rolldown/binding-win32-x64-msvc'
  - dompurify
  - electron-to-chromium
  - immer
  - lucide-react
  - mermaid
  - rolldown
  - uuid
  - '@opencode-ai/sdk@1.18.30'
  - '@types/react-dom@19.3.0'
  - '@types/react@19.3.0'
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
