allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@mermaid-js/parser'
  - '@oxc-project/types'
  - '@rolldown/binding-android-arm-eabi'
  - '@rolldown/binding-android-arm64'
  - '@rolldown/binding-darwin-arm64'
  - '@rolldown/binding-darwin-x64'
  - '@rolldown/binding-freebsd-x64'
  - '@rolldown/binding-linux-arm-gnueabihf'
  - '@rolldown/binding-linux-arm64-gnu'
  - '@rolldown/binding-linux-arm64-musl'
  - '@rolldown/binding-linux-ppc64-gnu'
  - '@rolldown/binding-linux-s390x-gnu'
  - '@rolldown/binding-linux-x64-gnu'
  - '@rolldown/binding-linux-x64-musl'
  - '@rolldown/binding-openharmony-arm64'
  - '@rolldown/binding-win32-arm64-msvc'
  - '@rolldown/binding-win32-x64-msvc'
  - dompurify
  - electron-to-chromium
  - immer
  - lucide-react
  - mermaid
  - rolldown
  - uuid
